version: "3.8"

networks:
  internal:

services:
  app:
    build: ./app/
    depends_on:
      - statsd_exporter
    environment:
      - DJANGO_MANAGEPY_MIGRATE=on
    expose:
      - "8000"      # gunicorn
      - "8001-8050" # django-prometheus
    networks:
      - internal

  nginx:
    depends_on:
      - app
    expose:
      - "8080"
    image: nginx:1.19
    networks:
      - internal
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  nginx_exporter:
    command: -nginx.scrape-uri=http://nginx:8080/nginx_status
    depends_on:
      - nginx
    expose:
      - "9113"
    image: nginx/nginx-prometheus-exporter:0.9.0
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v2.25.2
    networks:
      - internal
    expose:
      - "9091"
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  statsd_exporter:
    expose:
      - '9125'
      - '9125/udp'
    image: prom/statsd-exporter
    networks:
      - internal
    ports:
      - '9102:9102'

#  grafana:
#    image: grafana/grafana-enterprise:8.2.0
#    ports:
#      - 3000:3000

########################################

  prometheus_external:
    image: prom/prometheus:v2.25.2
    network_mode: host
    expose:
      - "9090"
    volumes:
      - ./prometheus_external/prometheus.yml:/etc/prometheus/prometheus.yml


